name: match-ci

on: [pull_request]

env:
  GOPATH: ${{ github.workspace }}

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go 1.22.2
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.2'
      - name: Install dependencies
        run: go get ./...
      - name: Run tests
        run: go test -v ./...
