name: match CI

on: [pull_request]

env:
  GOPATH: ${{ github.workspace }}

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: '${{ env.GOPATH }}/go.mod'
      - name: Install dependencies
        run: go get ./...
      - name: Run tests
        run: go test -v ./...
